import Router from '@koa/router';
// import getAnswer from './api/get-answer';
import playChat from './api/user/chat';
import registerUser from './api/user/register';
import loginUser from './api/user/login';
import getMyselfTopics from './api/user/get-myself-topics';
import createTopicByTopicId from './api/user/createTopicByTopicId';
import deleteTopic from './api/user/deleteTopic';
import clearTopics from './api/user/clearTopics';
import queryTopicMessages from './api/user/queryTopicMessages';
import regenerateContent from './api/user/regenerate-content';
import queryPrompts from './api/setting/queryPrompts';
const router = new Router();
// getAnswer(router);
playChat(router);
registerUser(router);
loginUser(router);
getMyselfTopics(router);
createTopicByTopicId(router);
deleteTopic(router);
clearTopics(router);
queryTopicMessages(router);
regenerateContent(router);
queryPrompts(router);
export default router;
